### ISSUE TITLE
Inaccurate thinking time

### ISSUE THREAD

**Issue by gonzalezjo** [scs-ben/tcec-gui#11]
Issue at hand: 

On both this GUI and the old one, on the first page load, the amount of time being spent on the current move is always initialized to zero. This makes it hard to tell how long an engine has spent on the current move, just after loading the page. Moreover, the amount of time spent on the current move could be inaccurate, depending on GUI lag. This would often lead to confusion, and is the reason why the Nightbot `!clock` command exists. (As of this moment, `!clock` outputs: "The time in the GUI is not official, and it is sometimes laggy.")

I haven't seen this implemented by any GUIs. If the Unix timestamp of the last move was included in live.json, we could always have an accurate thinking time for the engines, even with GUI lag, and even on the first page load.

**Comment by gonzalezjo** [comment]
Just subtract the system time from the timestamp the server says, and it will always be accurate. If you use Unix time, you can just feed it into the Date API and subtract it from the current system time, without worrying about timezones.

**Comment by scs-ben** [comment]
we found a way to get modified by for the file, this is resolved

**Comment by scs-ben** [comment]
This is basically fixed
