### ISSUE TITLE
TB Rules still refer to S11

### ISSUE THREAD

**Issue by tcecspectator** [scs-ben/tcec-gui#126]
Under Rules:

Endgame Tablebases
For Season 11 all divisions, 5-men Nalimov/Gaviota/Scorpio, and 6-men Syzygy are available thanks to the 256 GB SSD. When watching a game you can see the type of the tablebases (if any) that is in use for the engines currently playing by clicking the gears next to the engine logo.

**Comment by arunsathya1309** [comment]
fixed
