### ISSUE TITLE
backing out of "what if" scenarios on PV board

### ISSUE THREAD

**Issue by awbgithub** [scs-ben/tcec-gui#132]
As a user of TCEC I'd like to be able to play through different lines than what the engines choose to play - mainly to see if I can find where "my" line breaks down. The PV board is a great place to do this, but currently if I make a wrong move in my "what if" scenario and I click the "back" button then I can't choose to make a different move - I can only click further back or forward.

It would be great if after clicking "back" in my "what if" scenario then I could choose to play a different move than the one I had previously chosen to play.

The workaround is to click the move in the PV again that brings me back to the start fo my "what if" scenario and then make all the moves again up to the point where I want to try the variation - but that is not very convenient.

**Comment by arunsathya1309** [comment]
Test it out now

**Comment by arunsathya1309** [comment]
Works
