### ISSUE TITLE
Date format consistency

### ISSUE THREAD

**Issue by rackbrain** [scs-ben/tcec-gui#133]
In the past, the legacy archive used the "dd/mm/yyyy" format for dates. Now there is the USA "TCEC CUP 1 - 10.04.2018" for October 4th 2018. I strongly suggest that TCEC use the ISO format "yyyy/mm/dd" for all present and future dates on its websites.

**Comment by arunsathya1309** [comment]
For future events ill make it yyyy/mm/dd
