### ISSUE TITLE
Saving Stockfish live evaluation and PV

### ISSUE THREAD

**Issue by hadynthepadawan** [scs-ben/tcec-gui#137]
I have noticed that while navigating through the moves list during a live game, SF's live evaluation and PV are not saved and only the current's move eval and PV are displayed. I was wondering if the UI could save the eval and primary variation of the live SF kibitzer so that it could be displayed while navigating through the moves games. This could be helpful at discussing at what point the playing engines made a mistake, and it could be useful at pointing what SF live kibitzer was suggesting at that exact point in the game.

**Comment by arunsathya1309** [comment]
done
