### ISSUE TITLE
Some style and layout suggestions

### ISSUE THREAD

**Issue by nsousa254** [scs-ben/tcec-gui#14]
Hi all. 
Here are some suggestions by me, send through github as issue, as recommended by chat mods. Just a contribution, not a whine or demand :)

Intro
CCCC has raised the bar with respect to computer chess broadcast screen aspect. TCEC should update accordingly to stay competitive. No need pro stuff, but a nice, clean look will definitely help. The ballpark is, I'd say, to get at least as systematic in style as the old GUI (still) is.

My screen size
- MacBook Pro Retina

Overall
- I really think the board should be in the center. Consider swapping board with engine info column (logo, eval, pv, etc.). Right now there is a huge visual focus on the engine info, most of which is not very important.
- The html frames seem to be static in size. Can they be made to auto-adjust to browser window size? CCCC has that and works well. Static size also makes it harder to work on some window sizes.

Header
- Adj rule -> Adjudication rule. By the way, great idea to summarize the 3 adjudication rules in a single header.
- Result and round columns can be made a tad smaller, to give room to opening name, which can sometimes extend considerably and could use that extra space. (By the way the opening column is not displaying complete opening name like in TCEC main server.)

Board
- Suggest making it bigger. Seems a bit smallish as compared to other columns. 
- If possible, add support for multiple piece and board types.
- FEN button text expands out of box. A fast-fix could be replacing with a mere "F" or "FEN" icon, rather than text.

Engine info
- I don't think we need like 6-7 lines of pv text. It takes a lot of vertical space and it's not that important. People are only interested in the first few moves.. the full PV only matters if there is a small board attached. Unless a side board is implemented, 1-2 lines of pv text should be plenty (+scroll bar).
- Also, in night mode pv text background should be black, not grey. Same for the ETSDT graphs (eval/time/speed/depth/TB).
- They eval/clock/depth/TB layout looks a bit akward. I might send a suggestion for layout later. Perhaps this column can be made shorter in width, if board is made bigger.

Chat
- I know people want a large chat window. But actual size may use some tweaks. Width is probably ok (could be like 10% shorter), but height is a bit too high for my screen size. I need to either enter full-screen mode or hide the header to get a full view of chat.

Live eval box
- Would it be possible to make it one-line per engine, rather than multiple lines, as is currently forced by the PV column?

Standings box
- Change points with #games columns. The more relevant info is, the closer to engine name it should be.
- Some columns definitely can be made shorter.

Crosstable
- If possible, extend two-letter engine name abbreviations to three. Helps when engines have similar names.

**Comment by arunsathya1309** [comment]
Crosstable

    If possible, extend two-letter engine name abbreviations to three. Helps when engines have similar names.

whatever cutechess gives we display, ill ask jeremhia to make it 3

Standings box

    Change points with #games columns. The more relevant info is, the closer to engine name it should be.

[arun] I dont think so, its matter of ones preference

    Some columns definitely can be made shorter.
[arun] done

Chat

    I know people want a large chat window. But actual size may use some tweaks. Width is probably ok (could be like 10% shorter), but height is a bit too high for my screen size. I need to either enter full-screen mode or hide the header to get a full view of chat.

[arun] reduced it

Engine info

    I don't think we need like 6-7 lines of pv text. It takes a lot of vertical space and it's not that important. People are only interested in the first few moves.. the full PV only matters if there is a small board attached. Unless a side board is implemented, 1-2 lines of pv text should be plenty (+scroll bar).
[reduce size]

    Also, in night mode pv text background should be black, not grey. Same for the ETSDT graphs (eval/time/speed/depth/TB).
    They eval/clock/depth/TB layout looks a bit akward. I might send a suggestion for layout later. Perhaps this column can be made shorter in width, if board is made bigger.

[may be later]

Board

    Suggest making it bigger. Seems a bit smallish as compared to other columns.

    its big enough

    If possible, add support for multiple piece and board types.

   done

    FEN button text expands out of box. A fast-fix could be replacing with a mere "F" or "FEN" icon, rather than text.

   if you can give image of fen ill add it

**Comment by nsousa254** [comment]
Thanks fo your efforts. 

FEN
Will this FEN icon work?

<img width="62" alt="fen_icon" src="https://user-images.githubusercontent.com/15609839/45286979-14888c80-b4df-11e8-84d5-e04e2ff181d2.png">

**Comment by scs-ben** [comment]
if any issues remain, please open a new issue
