### ISSUE TITLE
Show version numbers of the engines being displayed in the section where PVs are shown.

### ISSUE THREAD

**Issue by anshulongithub** [scs-ben/tcec-gui#141]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/3238840/47256227-2b50c600-d431-11e8-86a4-05d980993f75.png">
In the image shown above, it will be useful to show the version number of the engines as well for which PVs are getting displayed.

**Comment by arunsathya1309** [comment]
very nice suggestion, added

**Comment by anshulongithub** [comment]
Thank you, Arun
