### ISSUE TITLE
Last move highlight not working

### ISSUE THREAD

**Issue by robertnurnberg** [scs-ben/tcec-gui#157]
Ticking or unticking the option for move highlight does not work, even after reload. I am using chromium on ubuntu.

Edit: Sorry, I saw that the move is highlighted, but very, very faint. Maybe an option to choose color, or thickness of highlight (zero being off) ? I should say that I am using the Wikipedia board theme, so its colours may prevent the move highlight to be seen properly.

**Comment by arunsathya1309** [comment]
move highlight size provided for both pv and main boards, shud satisfy ur requirement
