### ISSUE TITLE
Show not only wins number for each engine but also losses numbers.

### ISSUE THREAD

**Issue by Vizvezdenec** [scs-ben/tcec-gui#162]
Now it's showing only wins in round robins.
https://i.imgur.com/rFWUhZS.png
Sure, you can calculate the number of losses itself or see it on crosstable tab, but it wouldn't be easy when we will have a lot of engines in divisions next season.
Also will be interesting to see how many times engines lost as white/black.

**Comment by arunsathya1309** [comment]
done
