### ISSUE TITLE
Scores not getting updated correctly intermittently

### ISSUE THREAD

**Issue by arunsathya1309** [scs-ben/tcec-gui#164]
Few folks have said the score does not get updated correctly

**Comment by arunsathya1309** [comment]
New fix has been made, so shud work now properly

**Comment by arunsathya1309** [comment]
Should we close this issue and other issue then?

**Comment by LucyFair-TCEC** [comment]
yes. thank you once again
;-) --> https://www.youtube.com/watch?v=KsZHNqk_2gw

**Comment by arunsathya1309** [comment]
Closing this as it seems to be fixed and verified
