### ISSUE TITLE
save board notation setting across sessions

### ISSUE THREAD

**Issue by LucyFair-TCEC** [scs-ben/tcec-gui#166]
newuserxyz (Arun) requested this to track a "verified bug" ;-)

**Comment by LucyFair-TCEC** [comment]
first: i checked, and it is working. (it took me longer to check than for you to implement) :)
second: i stopped interfering with the session cookie, and guess what: between sessions, it is gone again, but the settings remain anyway. i'd like to understand, how persistant storage is working, for me to be able to take care of it and not be surprised again.

**Comment by arunsathya1309** [comment]
This was not ur fault, it was bug in GUI. We use https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by LucyFair-TCEC** [comment]
thank you. all problems resolved! :-)
yozr pointer led me to this: [https://stackoverflow.com/questions/8634058/where-the-sessionstorage-and-localstorage-stored](url)
