### ISSUE TITLE
PV control issue

### ISSUE THREAD

**Issue by Alayan-stk-2** [scs-ben/tcec-gui#169]
Steps to reproduce : 
1)Select Engine Info as the main tab
2)Select PV as the secondary tab (same line as "Eval", "Time", "Speed", etc)
3)The controls to move inside the PV don't work.

Additional relevant info : 
1)Select PV as the main tab
2)Select PV as the secondary tab
3)The PV controls from the main tab do work, and they also affect the PV board in the secondary tab.

**Comment by arunsathya1309** [comment]
Fixed,thanks for catching this,
