### ISSUE TITLE
Tournament setup

### ISSUE THREAD

**Issue by PerjorativePenguin** [scs-ben/tcec-gui#188]
I am concerned about how Chess tournaments such as TCEC are conducting their play.  For each Chess engine to be on equal footing EVERY engine must play EVERY other engine with the SAME opening as both white and black.  An example:

1_ 2 _ 3_ 4_ 5_ 6_ 7_ 8_    Each number corresponds to an individual Chess Engine.  Now we pick an opening to be played, and the games should be as follows.

12_ 13_ 14_ 15_ 16_ 17_ 18
23_ 24_ 25_ 26_ 27_ 28
34_ 35_ 36_ 37_ 38
45_ 46_ 47_ 48
56_ 57_ 58
67_ 68
78
Each of these numbers represents 2 games where each engine will have a chance to play as white and as black.  For all these games the same 1 opening is to be played.
This is the fair way to test the engines.  The current way of testing leaves a possibility of accidentally or deliberately favoring one engine over another.  

The formula to calculate how many games it would take to play 1 opening with N engines is as follows: 2{(N-1)+(N-2)+(N-3).......}  You keep going until you add a 0.

That said, I realize that it would take 56 games to play 1 opening with 8 engines competing, but that is what must be done to ensure an accurate measurement of engine strength.  

Here is my solution to the Tournament Organization.

There will be 5 divisions.  Each division will contain 5 engines.  Each division will play the SAME 20 openings.

After each division has finished the 5 winners will play in a new division.  They will play 20 new openings where 1 engine will be crowned champion.  

Example of how it will work:

Div 1: **A** B C D E
Div 2: **F** G H I J 
Div 3: **K** L M N O                  (Division winners are bold, and the divisions are setup in order of placing)
Div 4: **P** Q R S T
Div 5: **U** V W X Y

Winner Division: **A** F K P U       (A is the Grand Champion)

To crown 2nd and 3rd place you need to create a new division.

2/3 rd place Division: **B C** F G K    ( B and C finish 2nd and 3rd respectively)

If you are confused on how I did the 2nd/3rd place this video explains it nicely.

https://www.youtube.com/watch?v=i-xqRDwpilM

**Comment by scs-ben** [comment]
This is not a GUI concern. Please take this issue to the Discord https://discord.gg/EYuyrDr
