### ISSUE TITLE
font sizes for game moves and chat

### ISSUE THREAD

**Issue by xoto10** [scs-ben/tcec-gui#24]
I am using firefox on Linux on a PC. See picture [here](https://imgur.com/a/PJ1JynH) 

First of all the board colours (light/dark squares) are still wrong for me, they display correctly as the page loads then change as it finishes loading, so perhaps I am not seeing the latest version for some reason?

My point is that we need to zoom in enough to read the chat, and this makes the game moves below the board and in the PVs larger than necessary since they use a bigger font. I think it would be better if the moves and the chat were in a similar size font.

As a side issue, I would like to see PV boards if possible, I often view the final position to see how the engines expect the game to progress after many moves.

Thanks for your work. :-)

**Comment by Khagrin2** [comment]
I change font size in the chat via Inspector.  Snapshot below indicates how I do this.  In the snapshot, I have changed it from 100% to 14px ... a setting comfortable for me when the browser zoom is 80%.

https://www.dropbox.com/s/w5d5pfusj0rqb1z/TwitchFontChangeViaInspector.png?dl=0
