### ISSUE TITLE
Use color pickers for light and dark squares (and other things as you see fit)

### ISSUE THREAD

**Issue by Khagrin2** [scs-ben/tcec-gui#26]
Now that you are working on "themes", I make this suggestion since most board themes are pretty nasty in my opinion.  With color pickers, nobody can complain :)  If you want to retain themes, then provide a "custom" theme where you can use the color pickers.

**Comment by arunsathya1309** [comment]
If you provide me color codes i can surely add it, i need black white codes with a name for the theme

**Comment by Khagrin2** [comment]
Hi Arun,

As regards color-pickers ... I meant providing a way for users to pop up a
little window that allows the viewer to choose ANY color they like.

Perhaps just by clicking on a board's square ... e.g. click on a dark
square:  a little window pops up, user clicks on a color palette.  After
which (ideally) all of the dark square colors would update in real time.
When the user is satisfied with their selection they close the popup (or
just click outside of it) ... Essentially the way you pick colors via the
browser's Inspector.

Of course it would be just fine to hang such a thing off your options
menu.

Here is a link to such a utility and a demo ... it seems that it could be
embedded fairly easily in your code.  It would cost 16.00 for a license
that would allow you to use it in TCEC.  Looks pretty sweet ... but I'm
sure there are others as well.

http://jscolor.com/

I suggested this approach because no matter how many hard-coded themes you
might come up with ... well, users would always prefer to create their
own.  This doesn't preclude having some canned themes ... you could augment
those by taking the chess.com approach of a having a single user-defined
"custom" theme.

- K
