### ISSUE TITLE
Can't click on bottom of schedule list under Opera

### ISSUE THREAD

**Issue by KitingFree** [scs-ben/tcec-gui#28]
When switching to schedule view, a part of the bottom of the list is overlapped by the black square (twitch video view) such as it is impossible to click on bottom buttons (e.g., for changing page). Cf screen copy.

Environment: Opera 55.0, OSX 

![capture d ecran 2018-09-10 20 37 14](https://user-images.githubusercontent.com/34043782/45317217-9a392600-b539-11e8-8d36-b64a889a247d.png)

**Comment by arunsathya1309** [comment]
Try now and reopen if it exists
