### ISSUE TITLE
Crosstable style always dark (while selecting white for rest of the page)

### ISSUE THREAD

**Issue by KitingFree** [scs-ben/tcec-gui#29]
Whatever the page theme option (dark or white), the crosstable is always displayed with dark style (while the rest of the page including tables gracefully changes color when changing theme)

Env: Opera or Firefox on OSX

![capture d ecran 2018-09-10 20 49 18](https://user-images.githubusercontent.com/34043782/45317719-1a13c000-b53b-11e8-85bf-c18270e49a19.png)

**Comment by arunsathya1309** [comment]
Fixed in http://tcecbeta.chessdb.cn/beta/live.html
