### ISSUE TITLE
use main board to click through pv line

### ISSUE THREAD

**Issue by kanchess** [scs-ben/tcec-gui#3]
I miss sometimes the ability to look through pvs with a board, clicking moves one by one. 
I like the absence of pv boards as such, it is a much quieter view with less distraction, but would it be an idea to still allow for this on the main board, after which you could go back to the game with a single click somehow? To me this seems useful in LTC games.
So it will be like clicking moves in a pv line and the positions would then show up on the main board, and the game position resumed at a click elsewhere, anyway that was the idea.
You see, only the pv lines are presented, and the first few pv moves i can still imagine quickly and visualize, but the deeper pvs require quite the mental effort.

**Comment by scs-ben** [comment]
That’s possible. Another option is to put a board in the tabs with the cross table and schedule

**Comment by scs-ben** [comment]
I’d prefer a second board over changing the main board but perhaps there are clever ways of integrating them

**Comment by Aloril** [comment]
Another additional feature could be to add Stockfish in Javascript engine to it

**Comment by bugdebugger** [comment]
The beta now has a PV board. So this issues could be closed I guess.

@Aloril Maybe an another issues should be opened for the JS SF thing

**Comment by scs-ben** [comment]
I +1 the idea of making SF eval a new item
