### ISSUE TITLE
Playing Engines Info

### ISSUE THREAD

**Issue by JamesChessZero** [scs-ben/tcec-gui#30]
Dear developers my suggestion is to change the part of the GUI where the two playing engines information  is displayed. The info would be shown like [this](https://imgur.com/a/qOhEQ6k) . I have thought on it so that we can see each piece of info from both engines one next to the other making comparisons easier. 

Regarding the PV moves, I have thought on showing some of the first moves with scrollbar and/or adding them to the main board (as Kan suggested in issue #3 ) in the way that chessbomb does it.

Thanks a lot for all you work on TCEC :100:

**Comment by arunsathya1309** [comment]
this is implemented
