### ISSUE TITLE
Save screen space by placing header info between "ads"

### ISSUE THREAD

**Issue by Khagrin2** [scs-ben/tcec-gui#31]
Here is what I mean:  https://www.dropbox.com/s/zq632wmem88uw1a/BetaHeaderToSaveSpace.png?dl=0

(I would also suggest rearranging the header info as shown in the snapshot.)

**Comment by scs-ben** [comment]
That space will be filled with ads, I don't think Anton wants to remove the #1 space for ad revenue.
