### ISSUE TITLE
Twitch chat stays in dark mode when switching back to light mode

### ISSUE THREAD

**Issue by bugdebugger** [scs-ben/tcec-gui#32]
If you are in dark mode and switch back to light mode the twitch chat stays dark.
If you reload the page everything is fine (as the cookie was reset correctly)

It seems the `setLight` method in `tcec.js` is simply missing a call in the form of

`$('#chatright').attr('src', 'https://www.twitch.tv/embed/TCEC_Chess_TV/chat?popout');`

**Comment by arunsathya1309** [comment]
http://tcecbeta.chessdb.cn/beta/live.html
