### ISSUE TITLE
GUI - 1920x1080 Quantum mockup for Anton's consideration

### ISSUE THREAD

**Issue by Khagrin2** [scs-ben/tcec-gui#38]
Hi all ...

Please review this suggested layout.  This can best be accomplished by downloading and viewing at its 
native 1920x1080 resolution.  

https://www.dropbox.com/s/cf61gmzdbg3i54j/BetaQuantum_1920x1080.png?dl=0

I think Anton will approve :)  

I have been following viewer suggestions for many TCEC seasons regarding GUIs, and I expect this layout 
would make the great majority of folks quite happy.  It was based on the current (9/12/18) beta layout.  
I was careful to maintain the same "sizes" to support 3-column "swapping", and ease any development
tasks if undertaken.  

Some particular things to note:

- Many viewers continue to ask for PV boards, so these are included as a replacement 
for the "move lists" and each would allow a black/white engine or a kibizter PV to be loaded.
It may, in fact, be useful to load the 2 PV boards with different views by the same engine.

- Happily the eval graph can now plot the kibitzer.  I suggest that instead of putting 
a "header" above the graph that allows toggling of lines, the user could simply touch one 
of the color-coded eval bars (i.e. the 3 bars of stats below the graphs) to accomplish the 
toggling. Please avoid re-sizing the graph depending on whether "eval" or some other metric
is selected.  

- Regarding those eval bars:  (1) Note the easy comparison of engine metrics; (2) Please support
"hover" to show information regarding each metric ... including special info regarding
the kibitzer engine; (3) The bars are arranged so that if a kibitzer is not available,
then the blue bar can simply be hidden ... along with the PV board blue "picker" ... without
 disrupting the visual flow.

- I strongly suggest you avoid borders around most elements since borders are rendered
differently across browsers and end up causing misalignment grief.

- The majority of viewers prefer the important elements of "engine name", "clocks" etc.
to be immediately apparent. They also like being able to immediately determine which side is 
playing black/white.  Hence I've adopted a traditional layout in this regard.

- I have added in the Elo information since folks are typically interested.

- I have reserved adequate space for all "textual" information so long as a nice set
of cross-browser compatible fonts is used.  I suggest using "bold" judiciously if at all! 
There is also plenty of space for the "material diff", which, by using gray pieces (ala
lichess) should work well for dark or light themes.

- I have moved the main board navigation to the right side.  The move list below the main
board should support manipulation by "touch" and arrow keys (e.g. left, right, up, down, 
page start, page end).  I don't think an explicit scroll bar need be displayed (i.e. just
hide it or crop it).

- I encourage use of the CCCC design to toggle "Chat", "Info", "Rules", and
"Options" since there should never be a desire to see more than one of these at once.

- I reserved some space to the right of the header ad bar where announcements, trivia, news,
mission statement, or other short blurbs (e.g. useful links, etc.) could be placed.  These may 
best be updated on a daily basis to encourage viewers to "stop by" and see what's new.

- The Twitch chat can be customized easily via the html to change the colors and labels,
remove borders, etc.

- I suggest overlaying the "Donate" and "Subscribe" buttons over the chat control as 
shown.  That saves screen space, and puts them at a spot which is a great reminder to
"chatters" that their support would be appreciated.

- I have tested the layout with a variety of backgrounds, board colors, 3-column position
swaps etc. and I expect the layout will easily lend itself to user customization.  Viewers
are much more likely to return and stay longer if they have invested the time to make
things "look just right" for their satisfaction.

I realize that accomplishing a layout like this is a lot of work and would be
a challenging effort.  That said, given this mockup, a professional web designer should have
a big head start regarding layout, color possibilities, font possibilities,
positioning, etc.  (Estimated pro dev effort to accomplish faithful visual coherence ~ 3 days.)

I sincerely hope that even if the layout is discarded as "not for TCEC", that
some of the ideas presented here will be taken into consideration!

Thanks for your continuing time, effort, and support of TCEC ... and for taking 
the time to look this over :)

**Comment by scs-ben** [comment]
We have invested dozens of hours into the current beta site and to accomplish this would take dozens of additional hours and would be nearly a complete rewrite. Neither Arun nor I desire to do that again. We have real jobs and families. If these things are of such importance you can either fork the repository and begin making changes yourself or find a “professional web developer” who can do it in “3 days”. 

I think maybe you don’t understand that this layout is a lite more than stylistic changes and would require some substantial work to the supporting code.

I’m not saying this layout is wrong or “not for TCEC” but that there isn’t currently the man power available to accomplish this.

**Comment by scs-ben** [comment]
At this time we are going to stick with the current UI. Perhaps if it is redesigned in the future, you can help coordinate the styling.
