### ISSUE TITLE
Reversed captured pieces

### ISSUE THREAD

**Issue by lucabrivio** [scs-ben/tcec-gui#58]
The captured pieces are showed in reversed places at the time of writing, I think: differentially captured white pieces are beside white's name, and black ones beside black names! I guess this is not as intended. Thanks!

**Comment by bugdebugger** [comment]
A little picture to illustrate the problem. Black is a pawn up here but the 1 pawn advantage is displayed on the wrong engine.

![bw](https://user-images.githubusercontent.com/1424542/45597265-b3265900-b9c9-11e8-995a-038405cc285e.jpg)

**Comment by scs-ben** [comment]
I believe this is fixed now.
