### ISSUE TITLE
Invalid HTML issues

### ISSUE THREAD

**Issue by bugdebugger** [scs-ben/tcec-gui#59]
This is collection of low priority issues with the HTML markup

1. Two `<li>` tags after another which is invalid https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L56-L59
2. Two uses of `<div class="dropdown-divider"></div>` in the menu as a direct child of an `<ul>` which is invalid https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L66-L68 https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L123-L125
3. Block of invalid HTML. One `<a>` tag as a direct child of an `<ul>` which is invalid. The outer `<li>` contains a `<li>` as direct child which is invalid https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L173-L182
4. A dangling quote on the `class` attribute https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L273
5. There are two `<ul>` elements with the same id value `id="pills-tab"`
6. There is no element with the `id` `dropdown06` https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L59
7. Not an HTML issues but another dangling quote after `"Archive Page"` https://github.com/scs-ben/tcec-gui/blob/2c3202dfe5cb771d9080e964d55d03fdee400e5e/live.html#L665

**Comment by scs-ben** [comment]
I think I fixed all of these
