### ISSUE TITLE
Middle data panel cosmetic suggestions

### ISSUE THREAD

**Issue by Khagrin2** [scs-ben/tcec-gui#64]
This comment is primarily for the "material" part ... I would suggest a "darkgray" background for that table row so the pieces show very nicely.  Word "material" unnecessary.  From the snapshot you can see I have also re-arranged the rows a bit and changed things up ... that is just for me today, but perhaps you will find some changes in this regard pleasing as well.

https://www.dropbox.com/s/kzoxr615ng4xya5/BetaClubMiddleDataPanel.png?dl=0

**Comment by scs-ben** [comment]
For full consideration please provide a mock-up for day/light mode

**Comment by Khagrin2** [comment]
Ben,

Per your request:

https://www.dropbox.com/s/atd3b6skscigbdu/BetaClubMiddleDarkAndLight.png?dl=0

Some notes on how this was achieved via Inspector:

(1) rows were rearranged to put clocks at bottom ... this makes the font differential for them less jarring and easier to pick out from the other data
(2) line-heights on the rows have been adjusted (e.g. eval row)
(3) "black/white" icons are superscripted, engine font names larger
(4) Eval -> "Evaluation" TB -> "TB hits" (makes metric labels nicely same width) ...  "Engine","Material" and "Clock" labels removed for cleaner appearance, and these are self-explanatory and don't need labels
(5) dark theme background around engine names, logos and clocks is #333, i.e. page background
(6) light theme adjusted background around those elements to lightgrey
(7) I moved the spinning gears to after the move time, with 10px left margin to separate from clock ... seemed a better spot when I was running it, but maybe another spot is even better
(8) Material bar background color is transparent for light theme and #4f4f4f (or some similar) for dark theme to address initial suggestion

**Comment by arunsathya1309** [comment]
done
