### ISSUE TITLE
Engine evals capping at 6.5 in center info table.

### ISSUE THREAD

**Issue by tcecspectator** [scs-ben/tcec-gui#67]
When an engine's evaluation goes above 6.5, on the next opposing engines move the evaluation returns or caps back to 6.5.  i.e. Say SF playing Ginkgo - SF eval would show 8.53 then once Ginkgo plays its move the SF eval would return to 6.5.  Happens for both engines in this manner if the eval goes over 6.5

**Comment by arunsathya1309** [comment]
I also saw that, i have put in a fix, i am not closing it till i verify

**Comment by bugdebugger** [comment]
Still happens on tcec.chessdom.com as of now. 
![2](https://user-images.githubusercontent.com/1424542/45925722-553ec780-bf1b-11e8-8c14-e3f66aca2549.JPG)
![3](https://user-images.githubusercontent.com/1424542/45925723-5a037b80-bf1b-11e8-9766-e62e20099145.JPG)

**Comment by arunsathya1309** [comment]
fixed
