### ISSUE TITLE
Chat emoticon popup window is not scrollable in beta GUI 

### ISSUE THREAD

**Issue by z1bnc** [scs-ben/tcec-gui#7]
When using the beta GUI , if I click on the small emoticon in the lower right corner of the chat window , I get a popup window of useable emoticons. The problem is this popup window is **not** scrollable in the beta GUI. In the old GUI it was scrollable. Minor issue to be sure :)

Windows 10
Edge browser

**Comment by scs-ben** [comment]
we don't have control over what happens in Twitch, I don't see the emoticon popup as scrollable on old GUI or beta
