### ISSUE TITLE
Suggested Board Square colors for Arun

### ISSUE THREAD

**Issue by Khagrin2** [scs-ben/tcec-gui#70]
Per a request by Arun for such suggestions, here is a link that shows Brown, Green, Blue, and Red boards on both light and dark themes.  The color codes are included between the boards on the snapshot.  Perhaps these (or a couple you like, if any) can be added to your themes.

https://www.dropbox.com/s/dl2h69i1qm350bw/BoardColorsOnDarkAndLightTheme.png?dl=0

**Comment by arunsathya1309** [comment]
I liked your chose your own color thingy, ill try to get it ... added these colors for now
