### ISSUE TITLE
Button/images underneath board don't display on FFox/linux

### ISSUE THREAD

**Issue by LucyFair-TCEC** [scs-ben/tcec-gui#71]
[https://ufile.io/m3kb9](url)

**Comment by arunsathya1309** [comment]
It’s empty the window

**Comment by arunsathya1309** [comment]
Open with proper screen

**Comment by LucyFair-TCEC** [comment]
Ok: i see it now: site uses cross-scripting (to fontawesome.com) which i do not allow by default. As soon as i did permit that access, the pics do show up. => i am saying this for future reference in case anyone cares.  :-)

**Comment by LucyFair-TCEC** [comment]
btw: you closed this, while i was asleep, could not reply. not nice :(

**Comment by LucyFair-TCEC** [comment]
Github has very simple rights/privileges (and even simpler management for them).

If you are not a collaborator of a repo, then (in regards to issues)

    you can open issues
    you can comment on all existing issues (open or closed)
    you can close your own issues
    you can re-open your own issues *if you closed them yourself
    you cannot close or re-open issues opened by someone else
    you cannot re-open your own issues if a repo collaborator closed them

you should have waited for ME to close the issue. => else, this is bad communication, demotivating at the very least
