### ISSUE TITLE
Crosstable results not comprehensible/illegible

### ISSUE THREAD

**Issue by rackbrain** [scs-ben/tcec-gui#77]
For http://tcec.chessdom.com/live.html, the crosstable presents the following problems:
(a) The significance of the black/red/green colours is not obvious and not explained as a note;
(b) The green colour is effectively illegible.

**Comment by z1bnc** [comment]
I am also having trouble viewing the crosstable luminescent green on both mobile and desktop.

**Comment by flither** [comment]
I second that, normally green=good, red = bad. Crosstable is confusing to read now. Wouldn't it be better to underline every white-black pair of games, and make wins green and loses red, also making the colors less bright?

**Comment by arunsathya1309** [comment]
Fixed in http://tcecbeta.club/#/, check how this works
