### ISSUE TITLE
Square highlighting

### ISSUE THREAD

**Issue by Rocky640** [scs-ben/tcec-gui#79]
I really don't like those thick yellow boxes on the main chess board (and it is even worse in the small PV windows) 
The square highlighting and color is more subtle on the old GUI and I prefer that.

**Comment by arunsathya1309** [comment]
Agreed done on http://tcecbeta.club/#/ , still lighter than this , on other boards not visible

**Comment by Rocky640** [comment]
Thanks, it is an improvement, yet I suggest to change the highlight color to closely match the darker square according to the board theme.
