### ISSUE TITLE
Bandwidth friendliness

### ISSUE THREAD

**Issue by gonzalezjo** [scs-ben/tcec-gui#9]
I'm usually mostly on 3G, and I have a pretty bad data-plan, so bandwidth is a huge deal to me. I was peeking at the beta site and noticed that it used about 137 kilobytes per second over four minutes: https://i.imgur.com/iU4wXEZ.png. That's a gigabyte in two hours of chess! Worse, the amount of data requested per second increases over time! When I loaded the page, it was at about 200K bytes. Deep into an endgame, Komodo v. Chiron is now at 464K bytes.

There are a few things that could be done to help make the site more bandwidth friendly: 

1. Using Brotli and gzip on the server, to shrink bandwidth usage per-request. This might just be a band-aid, that doesn't address any underlying issues.

2. Requesting stuff from the server less often (probably suboptimal, because bonus games at short time controls can suffer.) 

3. Using websockets to push data only when necessary, and to minimize the amount of data sent. This is the approach that's probably closest thing to optimal, and it's the approach that KM's GUI used, but it's also a pain to get working because so much needs to be edited.

4. Minimizing the amount of data sent by the server. Per schedule request, at the moment (as of the creation of this issue, toward the beginning of div p) each schedule.json request is about 27K bytes. At the end of the endgame I am watching, each live.json request is 464K bytes. Each data.json request is 0.6K. crosstable.json is 12K. liveeval.json is 2K. If these numbers were brought down, the status quo might be good enough.

**Comment by gonzalezjo** [comment]
Personal opinion: 


It seems like a websocket is the most efficient approach. They have great browser support, allow binary data to be sent, and more easily enables a system with state. 


For example, on the initial websocket connection, the server can send the entire game through the websocket, with a status code that indicates that it's a game. Then, a live eval status code can be sent with a single float. Afterward, whenever a move is played, a move status code can be sent with a byte representing the move and side that played it. There is the added benefit of not having HTTP overhead. One downside, however, is the fact that compression of websocket data can be a bit rough. On the other hand, compressed HTTP shouldn't be anywhere near as efficient as binary-data websockets anyway.

**Comment by scs-ben** [comment]
Now you’ve got me thinking how much work it will be to convert to a framework like Vue.js so I can use web sockets.

**Comment by scs-ben** [comment]
Well there is no server side even broadcaster

**Comment by scs-ben** [comment]
We are very optimized here :D
