### ISSUE TITLE
Crosstable results do not appear to agree with Standings table or make sense

### ISSUE THREAD

**Issue by rackbrain** [scs-ben/tcec-gui#90]
For Stockfish, as at 11:01 on 24 Sep 2018, the Standings table shows 11 wins as white and 5 wins as black.
The Crosstable shows 8 wins coloured red and 8 wins coloured black. If the Crosstable supposed to be showing wins as white/black, then one of these tables is wrong; if not, then what is the meaning of the different colours in the Crosstable?

**Comment by CatoTheYoungerTCEC** [comment]
The Crosstable is not showing wins as white/black; it is showing opening pairs.  I think my answer resolves this one.

**Comment by rackbrain** [comment]
Yes, resolved. Thank you.
